version: "3"
services:
  db:
    image: "mariadb:5.7.30"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "wodemima"
  web:
    image: "phpmyadmin/phpmyadmin:5"
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "db"
      MYSQL_ROOT_PASSWORD: "wodemima"
    depends_on:
      - db
