version: "3"
services:
  db:
    image: "mariadb:lts-ubi9"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "wodemima"
    networks:
      - app-net
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    image: "phpmyadmin:5.2.2-apache"
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "db"
      MYSQL_ROOT_PASSWORD: "wodemima"
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - app-net

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      device: /home/xiaozhi/data/mysql-data
      o: bind

networks:
  app-net:
    driver: bridge
